### ISSUE TITLE
How to obtain a function call graph using NativeSummary?

### ISSUE THREAD

**Issue by Lwx1203** [security-pride/NativeSummary#1]
Hello!How can I use your tool to obtain a function call graph?

**Comment by am009** [comment]
Just obtained a new repacked apk file from the tool, then generate a call graph from that apk using existing tools like Soot.

**Comment by Lwx1203** [comment]
> Just obtained a new repacked apk file from the tool, then generate a call graph from that apk using existing tools like Soot.
Thank you for your reply, I will give it a try.
